<?php

namespace League\Flysystem\Util;

use ErrorException;
use finfo;

/**
 * @internal
 */
class MimeType
{
    protected static $extensionToMimeTypeMap = [
        '1km' => 'application/vnd.1000minds.decision-model+xml',
        '3g2' => 'video/3gpp2',
        '3gp' => 'audio/3gpp',
        '3gpp' => 'audio/3gpp',
        '3mf' => 'model/3mf',
        '7zip' => 'application/x-7z-compressed',
        'aa3' => 'audio/ATRAC-ADVANCED-LOSSLESS',
        'aac' => 'audio/aac',
        'aal' => 'audio/ATRAC-ADVANCED-LOSSLESS',
        'abc' => 'text/vnd.abc',
        'ac' => 'application/pkix-attr-cert',
        'ac2' => 'application/vnd.banana-accounting',
        'ac3' => 'audio/ac3',
        'adts' => 'audio/aac',
        'afp' => 'application/vnd.afpc.modca',
        'ai' => 'application/pdf',
        'aif' => 'audio/x-aiff',
        'aifc' => 'audio/x-aiff',
        'aiff' => 'audio/x-aiff',
        'apr' => 'application/vnd.lotus-approach',
        'artisan' => 'application/vnd.artisan+json',
        'asc' => 'application/pgp-signature',
        'ascii' => 'text/vnd.ascii-art',
        'asf' => 'application/vnd.ms-asf',
        'aso' => 'application/vnd.accpac.simply.aso',
        'ass' => 'audio/aac',
        'at3' => 'audio/ATRAC3',
        'atomdeleted' => 'application/atomdeleted+xml',
        'atx' => 'audio/ATRAC-X',
        'au' => 'audio/x-au',
        'auc' => 'application/tamp-apex-update-confirm',
        'avci' => 'image/avci',
        'avcs' => 'image/avcs',
        'avi' => 'video/x-msvideo',
        'azw3' => 'application/vnd.amazon.mobi8-ebook',
        'bdm' => 'application/vnd.syncml.dm+wbxml',
        'bin' => 'application/gltf-buffer',
        'bmi' => 'application/vnd.bmi',
        'bmp' => 'image/bmp',
        'bpmn' => 'application/octet-stream',
        'btf' => 'image/prs.btif',
        'btif' => 'image/prs.btif',
        'c3ex' => 'application/cccex',
        'cbor' => 'application/cbor',
        'cbr' => 'application/vnd.comicbook-rar',
        'cbz' => 'application/vnd.comicbook+zip',
        'ccc' => 'text/vnd.net2phone.commcenter.command',
        'ccmp' => 'application/ccmp+xml',
        'cdmia' => 'application/cdmi-capability',
        'cdmic' => 'application/cdmi-container',
        'cdmid' => 'application/cdmi-domain',
        'cdmio' => 'application/cdmi-object',
        'cdmiq' => 'application/cdmi-queue',
        'cdr' => 'application/cdr',
        'cer' => 'application/pkix-cert',
        'class' => 'application/octet-stream',
        'clue' => 'application/clue_info+xml',
        'cmsc' => 'application/cms',
        'cnd' => 'text/jcr-cnd',
        'cpt' => 'application/mac-compactpro',
        'crl' => 'application/pkix-crl',
        'crt' => 'application/x-x509-ca-cert',
        'csr' => 'application/octet-stream',
        'css' => 'text/css',
        'csv' => 'text/csv',
        'cuc' => 'application/tamp-community-update-confirm',
        'cw' => 'application/prs.cww',
        'cww' => 'application/prs.cww',
        'dcm' => 'application/dicom',
        'dcr' => 'application/x-director',
        'ddf' => 'application/vnd.syncml.dmddf+xml',
        'der' => 'application/x-x509-ca-cert',
        'dib' => 'image/bmp',
        'dir' => 'application/x-director',
        'disposition' => 'message/disposition-notification',
        'dive' => 'application/vnd.patentdive',
        'dll' => 'application/octet-stream',
        'dls' => 'audio/dls',
        'dmn' => 'application/octet-stream',
        'dms' => 'application/octet-stream',
        'doc' => 'application/msword',
        'docm' => 'application/vnd.ms-word.template.macroEnabled.12',
        'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'dot' => 'application/msword',
        'dotm' => 'application/vnd.ms-word.template.macroEnabled.12',
        'dotx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
        'drle' => 'image/dicom-rle',
        'dssc' => 'application/dssc+der',
        'dtd' => 'application/xml-dtd',
        'dvc' => 'application/dvcs',
        'dvi' => 'application/x-dvi',
        'dwd' => 'application/atsc-dwd+xml',
        'dxr' => 'application/x-director',
        'ecig' => 'application/vnd.evolv.ecig.settings',
        'ecigprofile' => 'application/vnd.evolv.ecig.profile',
        'ecigtheme' => 'application/vnd.evolv.ecig.theme',
        'efi' => 'application/efi',
        'emf' => 'image/emf',
        'eml' => 'message/rfc822',
        'emm' => 'application/vnd.ibm.electronic-media',
        'ent' => 'application/xml-external-parsed-entity',
        'eps' => 'application/postscript',
        'epub' => 'application/epub+zip',
        'es' => 'application/ecmascript',
        'espass' => 'application/vnd.espass-espass+zip',
        'exe' => 'application/octet-stream',
        'exr' => 'image/aces',
        'extension' => 'text/troff',
        'f4v' => 'video/mp4',
        'fdt' => 'application/fdt+xml',
        'fileinfo' => 'application/mp21',
        'fits' => 'application/fits',
        'flac' => 'audio/x-flac',
        'flb' => 'application/vnd.ficlab.flb+zip',
        'flt' => 'text/vnd.ficlab.flt',
        'fo' => 'application/vnd.software602.filler.form+xml',
        'fsc' => 'application/vnd.fsc.weblaunch',
        'g' => 'application/fdt+xml',
        'gbr' => 'application/rpki-ghostbusters',
        'geojson' => 'application/geo+json',
        'gif' => 'image/gif',
        'glb' => 'model/gltf-binary',
        'gltf' => 'model/gltf+json',
        'gml' => 'text/vnd.gml',
        'gpg' => 'application/gpg-keys',
        'gph' => 'application/vnd.FloGraphIt',
        'gpkg' => 'application/geopackage+sqlite3',
        'grd' => 'application/vnd.gentics.grd+json',
        'gsheet' => 'application/urc-grpsheet+xml',
        'gtar' => 'application/x-gtar',
        'gz' => 'application/gzip',
        'gzip' => 'application/x-gzip',
        'hdr' => 'image/vnd.radiance',
        'hdt' => 'application/vnd.hdt',
        'heic' => 'image/heic',
        'heics' => 'image/heic-sequence',
        'heif' => 'image/heic',
        'heifs' => 'image/heic-sequence',
        'hej2' => 'image/hej2k',
        'held' => 'application/atsc-held+xml',
        'heldxml' => 'application/held+xml',
        'hgl' => 'text/vnd.hgl',
        'hpub' => 'application/prs.hpub+zip',
        'hqx' => 'application/mac-binhex40',
        'hsj2' => 'image/hsj2',
        'htm' => 'text/html',
        'html' => 'text/html',
        'ics' => 'text/calendar',
        'ign' => 'application/vnd.coreos.ignition+json',
        'ignition' => 'application/vnd.coreos.ignition+json',
        'imf' => 'application/vnd.imagemeter.folder+zip',
        'img' => 'application/vnd.efi.img',
        'imgcal' => 'application/vnd.3lightssoftware.imagescal',
        'imi' => 'application/vnd.imagemeter.image+zip',
        'imp' => 'application/vnd.accpac.simply.imp',
        'ipfix' => 'application/ipfix',
        'iso' => 'application/vnd.efi.iso',
        'istc' => 'application/vnd.veryant.thin',
        'isws' => 'application/vnd.veryant.thin',
        'jar' => 'application/java-archive',
        'jhc' => 'image/jphc',
        'jls' => 'image/jls',
        'jp2' => 'image/jp2',
        'jpe' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'jpf' => 'image/jpx',
        'jpg' => 'image/jpeg',
        'jpg2' => 'image/jp2',
        'jpgm' => 'image/jpm',
        'jph' => 'image/jph',
        'jpm' => 'image/jpm',
        'jrd' => 'application/jrd+json',
        'js' => 'application/javascript',
        'json' => 'application/json',
        'jxr' => 'image/jxr',
        'jxra' => 'image/jxrA',
        'jxrs' => 'image/jxrS',
        'jxs' => 'image/jxs',
        'jxsc' => 'image/jxsc',
        'jxsi' => 'image/jxsi',
        'jxss' => 'image/jxss',
        'kdb' => 'application/octet-stream',
        'keynote' => 'application/vnd.apple.keynote',
        'kml' => 'application/vnd.google-earth.kml+xml',
        'kmz' => 'application/vnd.google-earth.kmz',
        'lasjson' => 'application/vnd.las.las+json',
        'latex' => 'application/x-latex',
        'lca' => 'application/vnd.logipipe.circuit+zip',
        'lcs' => 'application/vnd.logipipe.circuit+zip',
        'lgr' => 'application/lgr+xml',
        'lha' => 'application/octet-stream',
        'list3820' => 'application/vnd.afpc.modca',
        'listafp' => 'application/vnd.afpc.modca',
        'loas' => 'audio/aac',
        'log' => 'text/plain',
        'loom' => 'application/vnd.loom',
        'lostsyncxml' => 'application/lostsync+xml',
        'lwp' => 'application/vnd.lotus-wordpro',
        'lzh' => 'application/octet-stream',
        'm3u' => 'application/vnd.apple.mpegurl',
        'm3u8' => 'application/vnd.apple.mpegurl',
        'm4a' => 'audio/x-m4a',
        'm4s' => 'video/iso.segment',
        'm4u' => 'application/vnd.mpegurl',
        'mads' => 'application/mads+xml',
        'maei' => 'application/mmt-aei+xml',
        'markdown' => 'text/markdown',
        'mbox' => 'application/mbox',
        'mc2' => 'text/vnd.senx.warpscript',
        'mcd' => 'application/vnd.vectorworks',
        'md' => 'text/markdown',
        'mets' => 'application/mets+xml',
        'mft' => 'application/rpki-manifest',
        'mid' => 'audio/sp-midi',
        'midi' => 'audio/midi',
        'mif' => 'application/vnd.mif',
        'mj2' => 'video/mj2',
        'mjp2' => 'video/mj2',
        'mod' => 'application/xml-dtd',
        'mods' => 'application/mods+xml',
        'mov' => 'video/quicktime',
        'movie' => 'video/x-sgi-movie',
        'mp1' => 'audio/mpeg',
        'mp2' => 'audio/mpeg',
        'mp3' => 'audio/mpeg',
        'mp4' => 'application/mp4',
        'mpe' => 'video/mpeg',
        'mpeg' => 'video/mpeg',
        'mpf' => 'text/vnd.ms-mediapackage',
        'mpg' => 'video/mpeg',
        'mpg4' => 'application/mp4',
        'mpga' => 'audio/mpeg',
        'mpw' => 'application/vnd.exstream-empower+zip',
        'mrcx' => 'application/marcxml+xml',
        'multitrack' => 'audio/vnd.presonus.multitrack',
        'musd' => 'application/mmt-usd+xml',
        'mvt' => 'application/vnd.mapbox-vector-tile',
        'mxf' => 'application/mxf',
        'mxl' => 'application/vnd.recordare.musicxml',
        'mxmf' => 'audio/mobile-xmf',
        'mxml' => 'application/xv+xml',
        'net' => 'application/mp21',
        'nimn' => 'application/vnd.nimn',
        'nnd' => 'application/vnd.noblenet-directory',
        'nns' => 'application/vnd.noblenet-sealer',
        'nnw' => 'application/vnd.noblenet-web',
        'nq' => 'application/n-quads',
        'nsf' => 'application/vnd.lotus-notes',
        'nt' => 'application/n-triples',
        'numbers' => 'application/vnd.apple.numbers',
        'oda' => 'application/oda',
        'odb' => 'application/vnd.oasis.opendocument.database',
        'odc' => 'application/vnd.oasis.opendocument.chart',
        'odf' => 'application/vnd.oasis.opendocument.formula',
        'odg' => 'application/vnd.oasis.opendocument.graphics',
        'odi' => 'application/vnd.oasis.opendocument.image',
        'odm' => 'application/vnd.oasis.opendocument.text-master',
        'odp' => 'application/vnd.oasis.opendocument.presentation',
        'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
        'odt' => 'application/vnd.oasis.opendocument.text',
        'oga' => 'audio/ogg',
        'ogg' => 'audio/ogg',
        'ogv' => 'video/ogg',
        'ogx' => 'application/ogg',
        'omg' => 'audio/ATRAC-ADVANCED-LOSSLESS',
        'opf' => 'application/oebps-package+xml',
        'opus' => 'audio/ogg',
        'or3' => 'application/vnd.lotus-organizer',
        'orq' => 'application/ocsp-request',
        'ors' => 'application/ocsp-response',
        'osm' => 'application/vnd.openstreetmap.data+xml',
        'ota' => 'application/vnd.android.ota',
        'ott' => 'application/vnd.oasis.opendocument.text-template',
        'ovl' => 'application/vnd.afpc.modca-overlay',
        'oxps' => 'application/oxps',
        'p10' => 'application/pkcs10',
        'p12' => 'application/pkcs12',
        'p7a' => 'application/x-pkcs7-signature',
        'p7c' => 'application/pkcs7-mime',
        'p7m' => 'application/pkcs7-mime',
        'p7r' => 'application/x-pkcs7-certreqresp',
        'p7s' => 'application/pkcs7-signature',
        'p8' => 'application/pkcs8',
        'p8e' => 'application/pkcs8-encrypted',
        'pages' => 'application/vnd.apple.pages',
        'pdf' => 'application/pdf',
        'pem' => 'application/pem-certificate-chain',
        'pfr' => 'application/font-tdpfr',
        'pfx' => 'application/pkcs12',
        'pgn' => 'application/vnd.chess-pgn',
        'pgp' => 'application/pgp',
        'php' => 'application/x-httpd-php',
        'php3' => 'application/x-httpd-php',
        'php4' => 'application/x-httpd-php',
        'phps' => 'application/x-httpd-php-source',
        'phtml' => 'application/x-httpd-php',
        'pic' => 'image/vnd.radiance',
        'pkg' => 'application/vnd.exstream-package',
        'pkipath' => 'application/pkix-pkipath',
        'pml' => 'application/vnd.ctc-posml',
        'png' => 'image/png',
        'pot' => 'application/vnd.ms-powerpoint',
        'potm' => 'application/vnd.ms-powerpoint.presentation.macroEnabled.12',
        'potx' => 'application/vnd.openxmlformats-officedocument.presentationml.template',
        'ppa' => 'application/vnd.ms-powerpoint',
        'ppam' => 'application/vnd.ms-powerpoint.addin.macroEnabled.12',
        'pps' => 'application/vnd.ms-powerpoint',
        'ppsm' => 'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',
        'ppsx' => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
        'ppt' => 'application/powerpoint',
        'pptm' => 'application/vnd.ms-powerpoint.presentation.macroEnabled.12',
        'ppttc' => 'application/vnd.think-cell.ppttc+json',
        'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'provx' => 'application/provenance+xml',
        'prz' => 'application/vnd.lotus-freelance',
        'ps' => 'application/postscript',
        'psd' => 'application/x-photoshop',
        'pseg3820' => 'application/vnd.afpc.modca',
        'psfs' => 'application/vnd.psfs',
        'psg' => 'application/vnd.afpc.modca-pagesegment',
        'psid' => 'audio/prs.sid',
        'pub' => 'application/vnd.exstream-package',
        'qca' => 'application/vnd.ericsson.quickcall',
        'qcall' => 'application/vnd.ericsson.quickcall',
        'qt' => 'video/quicktime',
        'ra' => 'audio/x-realaudio',
        'ram' => 'audio/x-pn-realaudio',
        'rapd' => 'application/route-apd+xml',
        'rar' => 'application/vnd.rar',
        'rdf' => 'application/rdf+xml',
        'relo' => 'application/p2p-overlay+xml',
        'rfcxml' => 'application/rfc+xml',
        'rgbe' => 'image/vnd.radiance',
        'rm' => 'audio/x-pn-realaudio',
        'rnc' => 'application/relax-ng-compact-syntax',
        'roa' => 'application/rpki-roa',
        'rpm' => 'audio/x-pn-realaudio-plugin',
        'rsa' => 'application/x-pkcs7',
        'rsat' => 'application/atsc-rsat+xml',
        'rsheet' => 'application/urc-ressheet+xml',
        'rtf' => 'text/rtf',
        'rtx' => 'text/richtext',
        'rusd' => 'application/route-usd+xml',
        'rv' => 'video/vnd.rn-realvideo',
        'sac' => 'application/tamp-sequence-adjust-confirm',
        'sc' => 'application/vnd.ibm.secure-container',
        'scim' => 'application/scim+json',
        'scm' => 'application/vnd.lotus-screencam',
        'scq' => 'application/scvp-cv-request',
        'scs' => 'application/scvp-cv-response',
        'sdp' => 'application/sdp',
        'sea' => 'application/octet-stream',
        'senml' => 'application/senml+json',
        'senmlc' => 'application/senml+cbor',
        'senmle' => 'application/senml-exi',
        'senmlx' => 'application/senml+xml',
        'sensml' => 'application/sensml+json',
        'sensmlc' => 'application/sensml+cbor',
        'sensmle' => 'application/sensml-exi',
        'sensmlx' => 'application/sensml+xml',
        'shtml' => 'text/html',
        'sid' => 'audio/prs.sid',
        'sieve' => 'application/sieve',
        'sig' => 'application/pgp-signature',
        'sit' => 'application/x-stuffit',
        'siv' => 'application/sieve',
        'sls' => 'application/route-s-tsid+xml',
        'smi' => 'application/smil',
        'smil' => 'application/smil',
        'sml' => 'application/smil',
        'so' => 'application/octet-stream',
        'soa' => 'text/dns',
        'sos' => 'text/vnd.sosi',
        'spp' => 'application/scvp-vp-response',
        'spq' => 'application/scvp-vp-request',
        'spx' => 'audio/ogg',
        'sql' => 'application/sql',
        'sr' => 'application/vnd.sigrok.session',
        'sru' => 'application/sru+xml',
        'sst' => 'application/octet-stream',
        'ssv' => 'application/vnd.crypto-shade-file',
        'ssvc' => 'application/vnd.crypto-shade-file',
        'stf' => 'application/vnd.wt.stf',
        'stix' => 'application/stix+json',
        'stl' => 'model/stl',
        'svg' => 'image/svg+xml',
        'swf' => 'application/x-shockwave-flash',
        'swidtag' => 'application/swid+xml',
        't38' => 'image/t38',
        'tam' => 'application/vnd.onepager',
        'tamp' => 'application/vnd.onepagertamp',
        'tamx' => 'application/vnd.onepagertamx',
        'tar' => 'application/x-tar',
        'tat' => 'application/vnd.onepagertat',
        'tatp' => 'application/vnd.onepagertatp',
        'tatx' => 'application/vnd.onepagertatx',
        'tau' => 'application/tamp-apex-update',
        'tcu' => 'application/tamp-community-update',
        'ter' => 'application/tamp-error',
        'tex' => 'application/x-tex',
        'text' => 'text/plain',
        'tfx' => 'image/tiff-fx',
        'tgz' => 'application/x-tar',
        'tif' => 'image/tiff',
        'tiff' => 'image/tiff',
        'trig' => 'application/trig',
        'tsa' => 'application/tamp-sequence-adjust',
        'tsd' => 'application/timestamped-data',
        'tsq' => 'application/tamp-status-query',
        'tsr' => 'application/tamp-status-response',
        'ttml' => 'application/ttml+xml',
        'tuc' => 'application/tamp-update-confirm',
        'tur' => 'application/tamp-update',
        'txt' => 'text/prs.prop.logic',
        'u8dsn' => 'message/global-delivery-status',
        'u8mdn' => 'message/global-disposition-notification',
        'u8msg' => 'message/global',
        'uis' => 'application/urc-uisocketdesc+xml',
        'uo' => 'application/vnd.uoml+xml',
        'uoml' => 'application/vnd.uoml+xml',
        'uric' => 'text/vnd.si.uricatalogue',
        'usdz' => 'model/vnd.usdz+zip',
        'vcard' => 'text/vcard',
        'vcf' => 'text/vcard',
        'vcj' => 'application/voucher-cms+json',
        'ves' => 'application/vnd.ves.encrypted',
        'vlc' => 'application/videolan',
        'vpm' => 'multipart/voice-message',
        'vtt' => 'text/vtt',
        'vwx' => 'application/vnd.vectorworks',
        'wav' => 'audio/L16',
        'wbmp' => 'image/vnd.wap.wbmp',
        'wbxml' => 'application/vnd.wap.wmlc',
        'webm' => 'video/webm',
        'wlnk' => 'application/link-format',
        'wma' => 'audio/x-ms-wma',
        'wmf' => 'image/wmf',
        'wml' => 'text/vnd.wap.wml',
        'wmlc' => 'application/vnd.wap.wmlc',
        'wmls' => 'text/vnd.wap.wmlscript',
        'wmlsc' => 'application/vnd.wap.wmlscriptc',
        'wmv' => 'video/x-ms-wmv',
        'woff' => 'font/woff',
        'woff2' => 'font/woff2',
        'word' => 'application/msword',
        'xcs' => 'application/calendar+xml',
        'xdm' => 'application/vnd.syncml.dm+xml',
        'xdssc' => 'application/dssc+xml',
        'xhe' => 'audio/usac',
        'xht' => 'application/xhtml+xml',
        'xhtml' => 'application/xhtml+xml',
        'xhvml' => 'application/xv+xml',
        'xl' => 'application/excel',
        'xla' => 'application/vnd.ms-excel',
        'xlam' => 'application/vnd.ms-excel.addin.macroEnabled.12',
        'xlf' => 'application/xliff+xml',
        'xls' => 'application/vnd.ms-excel',
        'xlsb' => 'application/vnd.ms-excel.sheet.binary.macroEnabled.12',
        'xlsm' => 'application/vnd.ms-excel.sheet.macroEnabled.12',
        'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'xlt' => 'application/vnd.ms-excel',
        'xltm' => 'application/vnd.ms-excel.template.macroEnabled.12',
        'xltx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
        'xml' => 'application/xml',
        'xmls' => 'application/dskpp+xml',
        'xodp' => 'application/vnd.collabio.xodocuments.presentation',
        'xods' => 'application/vnd.collabio.xodocuments.spreadsheet',
        'xodt' => 'application/vnd.collabio.xodocuments.document',
        'xotp' => 'application/vnd.collabio.xodocuments.presentation-template',
        'xots' => 'application/vnd.collabio.xodocuments.spreadsheet-template',
        'xott' => 'application/vnd.collabio.xodocuments.document-template',
        'xsl' => 'application/xml',
        'xspf' => 'application/xspf+xml',
        'xvm' => 'application/xv+xml',
        'xvml' => 'application/xv+xml',
        'xyze' => 'image/vnd.radiance',
        'yt' => 'application/vnd.youtube.yt',
        'z' => 'application/x-compress',
        'zfc' => 'application/vnd.filmit.zfc',
        'zfo' => 'application/vnd.software602.filler.form-xml-zip',
        'zip' => 'application/vnd.iso11783-10+zip',
        'zone' => 'text/dns',
        'zsh' => 'text/x-scriptzsh',
        'zst' => 'application/zstd',
        '123' => 'application/vnd.lotus-1-2-3',
        '726' => 'audio/32kadpcm',
    ];

    /**
     * Detects MIME Type based on given content.
     *
     * @param mixed $content
     *
     * @return string|null MIME Type or NULL if no mime type detected
     */
    public static function detectByContent($content)
    {
        if ( ! class_exists('finfo') || ! is_string($content)) {
            return null;
        }
        try {
            $finfo = new finfo(FILEINFO_MIME_TYPE);

            return $finfo->buffer($content) ?: null;
            // @codeCoverageIgnoreStart
        } catch (ErrorException $e) {
            // This is caused by an array to string conversion error.
        }
    } // @codeCoverageIgnoreEnd

    /**
     * Detects MIME Type based on file extension.
     *
     * @param string $extension
     *
     * @return string|null MIME Type or NULL if no extension detected
     */
    public static function detectByFileExtension($extension)
    {
        return isset(static::$extensionToMimeTypeMap[$extension])
            ? static::$extensionToMimeTypeMap[$extension]
            : 'text/plain';
    }

    /**
     * @param string $filename
     *
     * @return string|null MIME Type or NULL if no extension detected
     */
    public static function detectByFilename($filename)
    {
        $extension = strtolower(pathinfo($filename, PATHINFO_EXTENSION));

        return empty($extension) ? 'text/plain' : static::detectByFileExtension($extension);
    }

    /**
     * @return array Map of file extension to MIME Type
     */
    public static function getExtensionToMimeTypeMap()
    {
        return static::$extensionToMimeTypeMap;
    }
}
